In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("ames_raw_data.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 83 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       2930 non-null   int64
 1   Order            2930 non-null   int64
 2   PID              2930 non-null   int64
 3   MS SubClass      2930 non-null   int64
 4   MS Zoning        2930 non-null   str
 5   Lot Frontage     2440 non-null   float64
 6   Lot Area         2930 non-null   int64
 7   Street           2930 non-null   str
 8   Alley            198 non-null    str
 9   Lot Shape        2930 non-null   str
 10  Land Contour     2930 non-null   str
 11  Utilities        2930 non-null   str
 12  Lot Config       2930 non-null   str
 13  Land Slope       2930 non-null   str
 14  Neighborhood     2930 non-null   str
 15  Condition 1      2930 non-null   str
 16  Condition 2      2930 non-null   str
 17  Bldg Type        2930 non-null   str
 18  House Style      2930 non-null   str
 19  Overall Qual     2930 non-null   int64
 20  Overall Cond     2930 non-null   int64
 21  Year Built       2930 non-null   int64
 22  Year Remod/Add   2930 non-null   int64
 23  Roof Style       2930 non-null   str
 24  Roof Matl        2930 non-null   str
 25  Exterior 1st     2930 non-null   str
 26  Exterior 2nd     2930 non-null   str
 27  Mas Vnr Type     1155 non-null   str
 28  Mas Vnr Area     2907 non-null   float64
 29  Exter Qual       2930 non-null   str
 30  Exter Cond       2930 non-null   str
 31  Foundation       2930 non-null   str
 32  Bsmt Qual        2850 non-null   str
 33  Bsmt Cond        2850 non-null   str
 34  Bsmt Exposure    2847 non-null   str
 35  BsmtFin Type 1   2850 non-null   str
 36  BsmtFin SF 1     2929 non-null   float64
 37  BsmtFin Type 2   2849 non-null   str
 38  BsmtFin SF 2     2929 non-null   float64
 39  Bsmt Unf SF      2929 non-null   float64
 40  Total Bsmt SF    2929 non-null   float64
 41  Heating          2930 non-null   str
 42  Heating QC       2930 non-null   str
 43  Central Air      2930 non-null   str
 44  Electrical       2929 non-null   str
 45  1st Flr SF       2930 non-null   int64
 46  2nd Flr SF       2930 non-null   int64
 47  Low Qual Fin SF  2930 non-null   int64
 48  Gr Liv Area      2930 non-null   int64
 49  Bsmt Full Bath   2928 non-null   float64
 50  Bsmt Half Bath   2928 non-null   float64
 51  Full Bath        2930 non-null   int64
 52  Half Bath        2930 non-null   int64
 53  Bedroom AbvGr    2930 non-null   int64
 54  Kitchen AbvGr    2930 non-null   int64
 55  Kitchen Qual     2930 non-null   str
 56  TotRms AbvGrd    2930 non-null   int64
 57  Functional       2930 non-null   str
 58  Fireplaces       2930 non-null   int64
 59  Fireplace Qu     1508 non-null   str
 60  Garage Type      2773 non-null   str
 61  Garage Yr Blt    2771 non-null   float64
 62  Garage Finish    2771 non-null   str
 63  Garage Cars      2929 non-null   float64
 64  Garage Area      2929 non-null   float64
 65  Garage Qual      2771 non-null   str
 66  Garage Cond      2771 non-null   str
 67  Paved Drive      2930 non-null   str
 68  Wood Deck SF     2930 non-null   int64
 69  Open Porch SF    2930 non-null   int64
 70  Enclosed Porch   2930 non-null   int64
 71  3Ssn Porch       2930 non-null   int64
 72  Screen Porch     2930 non-null   int64
 73  Pool Area        2930 non-null   int64
 74  Pool QC          13 non-null     str
 75  Fence            572 non-null    str
 76  Misc Feature     106 non-null    str
 77  Misc Val         2930 non-null   int64
 78  Mo Sold          2930 non-null   int64
 79  Yr Sold          2930 non-null   int64
 80  Sale Type        2930 non-null   str
 81  Sale Condition   2930 non-null   str
 82  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(29), str(43)
memory usage: 1.9 MB

In [4]:
df.shape

(2930, 83)

In [5]:
df.columns.to_list()

['Unnamed: 0',
 'Order',
 'PID',
 'MS SubClass',
 'MS Zoning',
 'Lot Frontage',
 'Lot Area',
 'Street',
 'Alley',
 'Lot Shape',
 'Land Contour',
 'Utilities',
 'Lot Config',
 'Land Slope',
 'Neighborhood',
 'Condition 1',
 'Condition 2',
 'Bldg Type',
 'House Style',
 'Overall Qual',
 'Overall Cond',
 'Year Built',
 'Year Remod/Add',
 'Roof Style',
 'Roof Matl',
 'Exterior 1st',
 'Exterior 2nd',
 'Mas Vnr Type',
 'Mas Vnr Area',
 'Exter Qual',
 'Exter Cond',
 'Foundation',
 'Bsmt Qual',
 'Bsmt Cond',
 'Bsmt Exposure',
 'BsmtFin Type 1',
 'BsmtFin SF 1',
 'BsmtFin Type 2',
 'BsmtFin SF 2',
 'Bsmt Unf SF',
 'Total Bsmt SF',
 'Heating',
 'Heating QC',
 'Central Air',
 'Electrical',
 '1st Flr SF',
 '2nd Flr SF',
 'Low Qual Fin SF',
 'Gr Liv Area',
 'Bsmt Full Bath',
 'Bsmt Half Bath',
 'Full Bath',
 'Half Bath',
 'Bedroom AbvGr',
 'Kitchen AbvGr',
 'Kitchen Qual',
 'TotRms AbvGrd',
 'Functional',
 'Fireplaces',
 'Fireplace Qu',
 'Garage Type',
 'Garage Yr Blt',
 'Garage Finish',
 'Garage Cars',
 'Garage Area',
 'Garage Qual',
 'Garage Cond',
 'Paved Drive',
 'Wood Deck SF',
 'Open Porch SF',
 'Enclosed Porch',
 '3Ssn Porch',
 'Screen Porch',
 'Pool Area',
 'Pool QC',
 'Fence',
 'Misc Feature',
 'Misc Val',
 'Mo Sold',
 'Yr Sold',
 'Sale Type',
 'Sale Condition',
 'SalePrice']

In [6]:
"SalePrice" in df.columns

True

In [7]:
df['SalePrice'].describe()

count      2930.000000
mean     180796.060068
std       79886.692357
min       12789.000000
25%      129500.000000
50%      160000.000000
75%      213500.000000
max      755000.000000
Name: SalePrice, dtype: float64

In [8]:
df.isnull().sum().sum()

np.int64(15749)

In [9]:
for i in range(0, len(df.columns), 10):
    print(f"\nColumns {i + 1} to {min(i + 10, len(df.columns))}:")
    print(df.columns[i:i + 10].tolist())

Columns 1 to 10:
['Unnamed: 0', 'Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area', 'Street', 'Alley', 'Lot Shape']

Columns 11 to 20:
['Land Contour', 'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual']

Columns 21 to 30:
['Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Mas Vnr Area', 'Exter Qual']

Columns 31 to 40:
['Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF']

Columns 41 to 50:
['Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath']

Columns 51 to 60:
['Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Fireplace Qu']

Columns 61 to 70:
['Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual', 'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF']

Columns 71 to 80:
['Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC', 'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold']

Columns 81 to 83:
['Sale Type', 'Sale Condition', 'SalePrice']

In [10]:
missing = df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

display(missing)

Pool QC           2917
Misc Feature      2824
Alley             2732
Fence             2358
Mas Vnr Type      1775
Fireplace Qu      1422
Lot Frontage       490
Garage Qual        159
Garage Cond        159
Garage Yr Blt      159
Garage Finish      159
Garage Type        157
Bsmt Exposure       83
BsmtFin Type 2      81
Bsmt Cond           80
Bsmt Qual           80
BsmtFin Type 1      80
Mas Vnr Area        23
Bsmt Full Bath       2
Bsmt Half Bath       2
BsmtFin SF 1         1
BsmtFin SF 2         1
Electrical           1
Total Bsmt SF        1
Bsmt Unf SF          1
Garage Area          1
Garage Cars          1
dtype: int64

In [11]:
cols=[
       "Pool QC",
    "Misc Feature",
    "Alley",
    "Fence",
    "Garage Type",
    "Garage Yr Blt",
    "Lot Frontage"
]

for col in cols:
    print(df[col].value_counts(dropna=False).head(10))

Pool QC
NaN    2917
Ex        4
Gd        4
TA        3
Fa        2
Name: count, dtype: int64
Misc Feature
NaN     2824
Shed      95
Gar2       5
Othr       4
Elev       1
TenC       1
Name: count, dtype: int64
Alley
NaN     2732
Grvl     120
Pave      78
Name: count, dtype: int64
Fence
NaN      2358
MnPrv     330
GdPrv     118
GdWo      112
MnWw       12
Name: count, dtype: int64
Garage Type
Attchd     1731
Detchd      782
BuiltIn     186
NaN         157
Basment      36
2Types       23
CarPort      15
Name: count, dtype: int64
Garage Yr Blt
NaN       159
2005.0    142
2006.0    115
2007.0    115
2004.0     99
2003.0     92
1977.0     66
2008.0     61
1998.0     59
2000.0     55
Name: count, dtype: int64
Lot Frontage
NaN     490
60.0    276
80.0    137
70.0    133
50.0    117
75.0    105
65.0     93
85.0     76
21.0     50
24.0     49
Name: count, dtype: int64

In [12]:
num_col=df.select_dtypes(include='number')
num_col.sum()

Unnamed: 0         4.293915e+06
Order              4.293915e+06
PID                2.093381e+12
MS SubClass        1.681450e+05
Lot Frontage       1.689080e+05
Lot Area           2.973341e+07
Overall Qual       1.785800e+04
Overall Cond       1.630000e+04
Year Built         5.776074e+06
Year Remod/Add     5.813901e+06
Mas Vnr Area       2.962140e+05
BsmtFin SF 1       1.296462e+06
BsmtFin SF 2       1.456370e+05
Bsmt Unf SF        1.638080e+06
Total Bsmt SF      3.080179e+06
1st Flr SF         3.397504e+06
2nd Flr SF         9.828860e+05
Low Qual Fin SF    1.370300e+04
Gr Liv Area        4.394093e+06
Bsmt Full Bath     1.263000e+03
Bsmt Half Bath     1.790000e+02
Full Bath          4.590000e+03
Half Bath          1.112000e+03
Bedroom AbvGr      8.363000e+03
Kitchen AbvGr      3.060000e+03
TotRms AbvGrd      1.887800e+04
Fireplaces         1.756000e+03
Garage Yr Blt      5.481405e+06
Garage Cars        5.175000e+03
Garage Area        1.384889e+06
Wood Deck SF       2.746930e+05
Open Porch SF      1.392730e+05
Enclosed Porch     6.742400e+04
3Ssn Porch         7.596000e+03
Screen Porch       4.688600e+04
Pool Area          6.573000e+03
Misc Val           1.483610e+05
Mo Sold            1.821300e+04
Yr Sold            5.882826e+06
SalePrice          5.297325e+08
dtype: float64

In [13]:
cat_col=df.select_dtypes(include='str')
cat_col

,MS Zoning,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,...,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Pool QC,Fence,Misc Feature,Sale Type,Sale Condition
0,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Attchd,Fin,TA,TA,P,NaN,NaN,NaN,WD,Normal
1,RH,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,Gar2,WD,Normal
3,RL,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal
4,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,Fin,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,RL,Pave,NaN,IR1,Lvl,AllPub,CulDSac,Gtl,Mitchel,Norm,...,Detchd,Unf,TA,TA,Y,NaN,GdPrv,NaN,WD,Normal
2926,RL,Pave,NaN,IR1,Low,AllPub,Inside,Mod,Mitchel,Norm,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
2927,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,...,NaN,NaN,NaN,NaN,Y,NaN,MnPrv,Shed,WD,Normal
2928,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2929,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [14]:
df.skew(numeric_only=True)

Unnamed: 0          0.000000
Order               0.000000
PID                 0.055886
MS SubClass         1.357579
Lot Frontage        1.499067
Lot Area           12.820898
Overall Qual        0.190634
Overall Cond        0.574429
Year Built         -0.604462
Year Remod/Add     -0.451863
Mas Vnr Area        2.606985
BsmtFin SF 1        1.416182
BsmtFin SF 2        4.139978
Bsmt Unf SF         0.923053
Total Bsmt SF       1.156204
1st Flr SF          1.469429
2nd Flr SF          0.866457
Low Qual Fin SF    12.118162
Gr Liv Area         1.274110
Bsmt Full Bath      0.616639
Bsmt Half Bath      3.940795
Full Bath           0.171952
Half Bath           0.697713
Bedroom AbvGr       0.305694
Kitchen AbvGr       4.313825
TotRms AbvGrd       0.753543
Fireplaces          0.739215
Garage Yr Blt      -0.384672
Garage Cars        -0.219836
Garage Area         0.241994
Wood Deck SF        1.842678
Open Porch SF       2.535386
Enclosed Porch      4.014446
3Ssn Porch         11.403795
Screen Porch        3.957467
Pool Area          16.939142
Misc Val           21.999788
Mo Sold             0.192596
Yr Sold             0.134862
SalePrice           1.743500
dtype: float64

In [15]:
df.corr(numeric_only=True)

,Unnamed: 0,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
Unnamed: 0,1.000000,1.000000,0.173593,0.011797,-0.007034,0.031354,-0.048500,-0.011054,-0.052319,-0.075566,...,-0.011292,0.016355,0.027908,-0.024975,0.004307,0.052518,-0.006083,0.133365,-0.975993,-0.031408
Order,1.000000,1.000000,0.173593,0.011797,-0.007034,0.031354,-0.048500,-0.011054,-0.052319,-0.075566,...,-0.011292,0.016355,0.027908,-0.024975,0.004307,0.052518,-0.006083,0.133365,-0.975993,-0.031408
PID,0.173593,0.173593,1.000000,-0.001281,-0.096918,0.034868,-0.263147,0.104451,-0.343388,-0.157111,...,-0.051135,-0.071311,0.162519,-0.024894,-0.025735,-0.002845,-0.008260,-0.050455,0.009579,-0.246521
MS SubClass,0.011797,0.011797,-0.001281,1.000000,-0.420135,-0.204613,0.039419,-0.067349,0.036579,0.043397,...,-0.017310,-0.014823,-0.022866,-0.037956,-0.050614,-0.003434,-0.029254,0.000350,-0.017905,-0.085092
Lot Frontage,-0.007034,-0.007034,-0.096918,-0.420135,1.000000,0.491313,0.212042,-0.074448,0.121562,0.091712,...,0.120084,0.163040,0.012758,0.028564,0.076666,0.173947,0.044476,0.011085,-0.007547,0.357318
Lot Area,0.031354,0.031354,0.034868,-0.204613,0.491313,1.000000,0.097188,-0.034759,0.023258,0.021682,...,0.157212,0.103760,0.021868,0.016243,0.055044,0.093775,0.069188,0.003859,-0.023085,0.266549
Overall Qual,-0.048500,-0.048500,-0.263147,0.039419,0.212042,0.097188,1.000000,-0.094812,0.597027,0.569609,...,0.255663,0.298412,-0.140332,0.018240,0.041615,0.030399,0.005179,0.031103,-0.020719,0.799262
Overall Cond,-0.011054,-0.011054,0.104451,-0.067349,-0.074448,-0.034759,-0.094812,1.000000,-0.368773,0.047680,...,0.020344,-0.068934,0.071459,0.043852,0.044055,-0.016787,0.034056,-0.007295,0.031207,-0.101697
Year Built,-0.052319,-0.052319,-0.343388,0.036579,0.121562,0.023258,0.597027,-0.368773,1.000000,0.612095,...,0.228964,0.198365,-0.374364,0.015803,-0.041436,0.002213,-0.011011,0.014577,-0.013197,0.558426
Year Remod/Add,-0.075566,-0.075566,-0.157111,0.043397,0.091712,0.021682,0.569609,0.047680,0.612095,1.000000,...,0.217857,0.241748,-0.220383,0.037412,-0.046888,-0.011410,-0.003132,0.018048,0.032652,0.532974
Mas Vnr Area,-0.030907,-0.030907,-0.229283,0.002730,0.222407,0.126830,0.429418,-0.135340,0.313292,0.196928,...,0.165467,0.143748,-0.110787,0.013778,0.065643,0.004617,0.044934,-0.000276,-0.017715,0.508285
BsmtFin SF 1,-0.032321,-0.032321,-0.098375,-0.060075,0.215583,0.191555,0.284118,-0.050935,0.279870,0.151790,...,0.224010,0.124947,-0.100455,0.050541,0.095874,0.084140,0.092886,-0.001155,0.022397,0.432914
BsmtFin SF 2,-0.002773,-0.002773,-0.001145,-0.070946,0.045999,0.083150,-0.041287,0.041134,-0.027415,-0.062129,...,0.098528,-0.005587,0.032380,-0.023325,0.062951,0.044398,-0.005204,-0.009484,0.007105,0.005891
Bsmt Unf SF,0.005780,0.005780,-0.087707,-0.130421,0.116743,0.023658,0.270058,-0.136819,0.128998,0.164805,...,-0.039621,0.118880,0.006229,-0.005446,-0.048083,-0.031999,-0.010166,0.021569,-0.036384,0.182855
Total Bsmt SF,-0.028719,-0.028719,-0.189642,-0.219445,0.353773,0.253589,0.547294,-0.173344,0.407526,0.297481,...,0.229931,0.245627,-0.085225,0.037871,0.075341,0.072128,0.083904,0.016678,-0.010405,0.632280
1st Flr SF,-0.013201,-0.013201,-0.141902,-0.247828,0.457391,0.332235,0.477837,-0.157052,0.310463,0.242108,...,0.227131,0.238041,-0.065713,0.044061,0.098316,0.121821,0.093003,0.040496,-0.013667,0.621676
2nd Flr SF,-0.000417,-0.000417,-0.003289,0.304237,0.029187,0.032996,0.241402,0.006218,0.016828,0.158939,...,0.089097,0.184538,0.055429,-0.032172,0.011741,0.044602,-0.005078,0.013247,-0.018530,0.269373
Low Qual Fin SF,0.013589,0.013589,0.056940,0.025765,0.005249,0.000812,-0.048680,0.009175,-0.144282,-0.060365,...,-0.015646,-0.000761,0.087326,-0.004505,0.006943,0.035200,-0.005939,0.011397,-0.002074,-0.037660
Gr Liv Area,-0.009342,-0.009342,-0.107579,0.068061,0.383822,0.285599,0.570556,-0.115643,0.241726,0.316855,...,0.250153,0.340857,0.004030,0.006481,0.086804,0.135463,0.067252,0.043665,-0.026489,0.706780
Bsmt Full Bath,-0.042539,-0.042539,-0.037759,0.013701,0.108915,0.125877,0.167858,-0.042766,0.211849,0.134387,...,0.186945,0.082268,-0.069235,0.027034,0.052208,0.043705,-0.004868,-0.003471,0.044905,0.276050
Bsmt Half Bath,0.024978,0.024978,0.004328,-0.003329,-0.024724,0.026903,-0.041647,0.084455,-0.030626,-0.046292,...,0.051430,-0.035069,-0.009334,0.026954,0.042326,0.066902,0.036982,0.022699,-0.019529,-0.035835
Full Bath,-0.044985,-0.044985,-0.171431,0.134631,0.184521,0.127433,0.522263,-0.214316,0.469406,0.457266,...,0.179574,0.258675,-0.117795,0.015435,-0.015130,0.028205,-0.009771,0.046032,-0.004754,0.545604
Half Bath,-0.039749,-0.039749,-0.166636,0.175879,0.041880,0.035497,0.268853,-0.088127,0.269268,0.211771,...,0.115212,0.180704,-0.081312,-0.023231,0.035990,0.001515,0.026648,-0.001311,0.001561,0.285056
Bedroom AbvGr,0.015424,0.015424,0.006345,-0.019208,0.240442,0.136569,0.063291,-0.006137,-0.055093,-0.021536,...,0.029711,0.083650,0.052115,-0.047151,0.009250,0.036707,0.000887,0.053677,-0.018008,0.143913
Kitchen AbvGr,-0.017685,-0.017685,0.076470,0.257698,0.005407,-0.020301,-0.159744,-0.086386,-0.137852,-0.142404,...,-0.087410,-0.068283,0.027911,-0.021379,-0.056337,-0.013066,0.025145,0.035201,0.035421,-0.119814
TotRms AbvGrd,0.002612,0.002612,-0.068981,0.031898,0.353137,0.216597,0.380693,-0.089816,0.111919,0.197528,...,0.154735,0.235684,0.017221,-0.025097,0.033731,0.072103,0.061134,0.043784,-0.030498,0.495474
Fireplaces,-0.019156,-0.019156,-0.108056,-0.049955,0.257255,0.256989,0.393007,-0.031702,0.170672,0.133322,...,0.228064,0.159637,-0.000250,0.018414,0.168004,0.098449,0.008192,0.032152,-0.007612,0.474558
Garage Yr Blt,-0.051160,-0.051160,-0.256829,0.088754,0.076306,-0.008952,0.570569,-0.326017,0.834849,0.652310,...,0.221991,0.231240,-0.300879,0.020617,-0.062515,-0.014513,-0.009265,0.024498,-0.005159,0.526965
Garage Cars,-0.036185,-0.036185,-0.237484,-0.045883,0.308706,0.179512,0.599545,-0.181557,0.537443,0.425403,...,0.241226,0.204182,-0.132840,0.023345,0.043012,0.030393,-0.016948,0.049847,-0.022488,0.647877
Garage Area,-0.035435,-0.035435,-0.210606,-0.103239,0.358505,0.212822,0.563503,-0.153754,0.480131,0.376438,...,0.238371,0.232912,-0.106272,0.029458,0.062436,0.053051,0.008466,0.039544,-0.013018,0.640401
Wood Deck SF,-0.011292,-0.011292,-0.051135,-0.017310,0.120084,0.157212,0.255663,0.020344,0.228964,0.217857,...,1.000000,0.039243,-0.119136,-0.003967,-0.052191,0.094156,0.056820,0.016974,0.000882,0.327143
Open Porch SF,0.016355,0.016355,-0.071311,-0.014823,0.163040,0.103760,0.298412,-0.068934,0.198365,0.241748,...,0.039243,1.000000,-0.059875,-0.009458,0.047548,0.064135,0.077254,0.033651,-0.037467,0.312951
Enclosed Porch,0.027908,0.027908,0.162519,-0.022866,0.012758,0.021868,-0.140332,0.071459,-0.374364,-0.220383,...,-0.119136,-0.059875,1.000000,-0.032674,-0.063965,0.092596,0.008773,-0.021324,-0.000505,-0.128787
3Ssn Porch,-0.024975,-0.024975,-0.024894,-0.037956,0.028564,0.016243,0.018240,0.043852,0.015803,0.037412,...,-0.003967,-0.009458,-0.032674,1.000000,-0.029430,-0.006501,-0.000753,0.027229,0.022668,0.032225
Screen Porch,0.004307,0.004307,-0.025735,-0.050614,0.076666,0.055044,0.041615,0.044055,-0.041436,-0.046888,...,-0.052191,0.047548,-0.063965,-0.029430,1.000000,0.026383,0.007162,0.028169,-0.006116,0.112151
Pool Area,0.052518,0.052518,-0.002845,-0.003434,0.173947,0.093775,0.030399,-0.016787,0.002213,-0.011410,...,0.094156,0.064135,0.092596,-0.006501,0.026383,1.000000,0.011942,-0.042223,-0.052541,0.068403
Misc Val,-0.006083,-0.006083,-0.008260,-0.029254,0.044476,0.069188,0.005179,0.034056,-0.011011,-0.003132,...,0.056820,0.077254,0.008773,-0.000753,0.007162,0.011942,1.000000,0.007333,0.008574,-0.015691
Mo Sold,0.133365,0.133365,-0.050455,0.000350,0.011085,0.003859,0.031103,-0.007295,0.014577,0.018048,...,0.016974,0.033651,-0.021324,0.027229,0.028169,-0.042223,0.007333,1.000000,-0.155554,0.035259
Yr Sold,-0.975993,-0.975993,0.009579,-0.017905,-0.007547,-0.023085,-0.020719,0.031207,-0.013197,0.032652,...,0.000882,-0.037467,-0.000505,0.022668,-0.006116,-0.052541,0.008574,-0.155554,1.000000,-0.030569
SalePrice,-0.031408,-0.031408,-0.246521,-0.085092,0.357318,0.266549,0.799262,-0.101697,0.558426,0.532974,...,0.327143,0.312951,-0.128787,0.032225,0.112151,0.068403,-0.015691,0.035259,-0.030569,1.000000

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [17]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(['SalePrice'],axis=1),df['SalePrice'],test_size=0.2,random_state=42)

In [18]:
print(x_test.shape)
print(x_train.shape)

(586, 82)
(2344, 82)

In [19]:
cat_col=list(x_train.select_dtypes(exclude=np.number).columns)
num_col=list(x_train.select_dtypes(include=np.number).columns)

In [20]:
num_pipeline=Pipeline([
    ('imputer',SimpleImputer(strategy='median'))
])
cat_pipeline=Pipeline(
    [
        ('imputer',SimpleImputer(
            strategy='constant',
            fill_value='Missing'
        )),
        ("encoder",OneHotEncoder(handle_unknown='ignore'))
    ]
)

In [21]:
processor=ColumnTransformer(
    [
        ('num',num_pipeline,num_col),
        ('cat',cat_pipeline,cat_col)
    ]
)

In [22]:
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline

In [23]:
model=Pipeline(
    [
        
          ('processor',processor),
            ('xgb',XGBRegressor(
                objective="reg:squarederror",
                n_estimators=300,
                learning_rate=0.05,
                max_depth=4,
                random_state=42,
                n_jobs=-1
            
            )),
        ]
)

In [24]:
model.fit(x_train,y_train)

Pipeline(steps=[('processor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Unnamed: 0', 'Order', 'PID',
                                                   'MS SubClass',
                                                   'Lot Frontage', 'Lot Area',
                                                   'Overall Qual',
                                                   'Overall Cond', 'Year Built',
                                                   'Year Remod/Add',
                                                   'Mas Vnr Area',
                                                   'BsmtFin SF 1',
                                                   'BsmtFin SF 2',
                                                   'Bsmt Unf SF',
                                                   'Total Bsmt SF',
                                                   '1st Flr SF', '2nd Flr SF',
                                                   'Low Qual Fin S...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=4, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [25]:
y_pred=model.predict(x_test)

In [26]:

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 14622.6552734375
MSE: 548999360.0
RMSE: 23430.73537044879
R2 Score: 0.9315252900123596

In [28]:
print(model.score(x_train,y_train))
print(model.score(x_test,y_test))

0.9796819686889648
0.9315252900123596